/**
 * Tests were generated by ChatGPT.
 * Test may have been modified by hand.
 */
import { describe, expect, it } from "vitest";
import type { ComponentList } from "./types.js";

import {
  replaceTag,
  getTagContents,
  getFirstComponent,
  getTag,
  extractScriptTags,
  minifyHtml,
  extractProps,
  injectProps,
  extractNamedSlotContent,
  replaceNamedSlots,
  extractDefaultSlotContent,
  extractInheritableAttributes,
  mergeAttributesOntoRoot,
} from "./components.js";

describe("extractScriptTags", () => {
  it("should extract one script tag", () => {
    const htmlString =
      "<html><body><script>alert('hello world')</script></body></html>";
    const expected = "<script>alert('hello world')</script>";
    expect(extractScriptTags(htmlString)).toEqual(expected);
  });

  it("should extract multiple script tags", () => {
    const htmlString = `
      <html>
        <body>
          <script>alert('hello world')</script>
          <script>console.log('goodbye world')</script>
        </body>
      </html>`;
    const expected = `<script>alert('hello world')</script>\n<script>console.log('goodbye world')</script>`;
    expect(extractScriptTags(htmlString)).toEqual(expected);
  });

  it("should not extract script tags that are commented out", () => {
    const htmlString = `
      <html>
        <body>
          <!-- <script>alert('hello world')</script> -->
          <script>console.log('goodbye world')</script>
        </body>
      </html>`;
    const expected = `<script>console.log('goodbye world')</script>`;
    expect(extractScriptTags(htmlString)).toEqual(expected);
  });

  it("should return an empty string if no script tags are found", () => {
    const htmlString = "<html><body><div>Hello world</div></body></html>";
    const expected = "";
    expect(extractScriptTags(htmlString)).toEqual(expected);
  });
});

describe("replaceTag", () => {
  it("replaces a single tag", () => {
    const input = "<div>before</div><span>replace me</span><div>after</div>";
    const output = "<div>before</div><p>new tag</p><div>after</div>";
    expect(replaceTag(input, "span", "<p>new tag</p>")).toEqual(output);
  });

  it("replaces only the first instance of a tag", () => {
    const input =
      "<div>before</div><span>replace me</span><span>do not replace me</span><div>after</div>";
    const output =
      "<div>before</div><p>new tag</p><span>do not replace me</span><div>after</div>";
    expect(replaceTag(input, "span", "<p>new tag</p>")).toEqual(output);
  });

  it("does not modify input when tag not found", () => {
    const input = "<div>before</div><p>do not replace me</p><div>after</div>";
    expect(replaceTag(input, "span", "<p>new tag</p>")).toEqual(input);
  });

  it("preserves tag attributes", () => {
    const input =
      '<div>before</div><span class="important">replace me</span><div>after</div>';
    const output =
      '<div>before</div><p class="important">new tag</p><div>after</div>';
    expect(
      replaceTag(input, "span", '<p class="important">new tag</p>'),
    ).toEqual(output);
  });

  it("is case-insensitive", () => {
    const input = "<div>before</div><SPAN>replace me</SPAN><div>after</div>";
    const output = "<div>before</div><p>new tag</p><div>after</div>";
    expect(replaceTag(input, "span", "<p>new tag</p>")).toEqual(output);
  });
});

describe("getTagContents", () => {
  it("gets contents of single tag", () => {
    const input = "<div>before</div><span>get me</span><div>after</div>";
    const output = { content: "<span>get me</span>", innerContent: "get me" };
    expect(getTagContents(input, "span")).toEqual(output);
  });

  it("gets contents of first matching tag", () => {
    const input =
      "<div>before</div><span>get me</span><span>not me</span><div>after</div>";
    const output = { content: "<span>get me</span>", innerContent: "get me" };
    expect(getTagContents(input, "span")).toEqual(output);
  });

  it("returns empty object when tag not found", () => {
    const input = "<div>before</div><p>do not get me</p><div>after</div>";
    const output = {};
    expect(getTagContents(input, "span")).toEqual(output);
  });

  it("preserves tag attributes", () => {
    const input =
      '<div>before</div><span class="important">get me</span><div>after</div>';
    const output = {
      content: '<span class="important">get me</span>',
      innerContent: "get me",
    };
    expect(getTagContents(input, "span")).toEqual(output);
  });

  it("is case-insensitive", () => {
    const input = "<div>before</div><SPAN>get me</SPAN><div>after</div>";
    const output = { content: "<SPAN>get me</SPAN>", innerContent: "get me" };
    expect(getTagContents(input, "span")).toEqual(output);
  });
});

describe("getTag", () => {
  const htmlString = `
    <div class="container">
      <h1>Welcome to my website</h1>
      <p>This is a test paragraph</p>
    </div>
  `;
  // Test component list with extra metadata — cast because these have non-standard properties
  const componentList = {
    div: { className: "container" },
    h1: { style: { fontWeight: "bold" } },
  } as unknown as ComponentList;

  it("returns content and inner content of tag", () => {
    const tagName = "p";
    const expectedOutput = {
      content: "<p>This is a test paragraph</p>",
      innerContent: "This is a test paragraph",
    };
    expect(getTag(htmlString, tagName)).toEqual(expectedOutput);
  });

  it("returns empty object when tag not found", () => {
    const tagName = "span";
    expect(getTag(htmlString, tagName)).toEqual({});
  });

  it("returns content, inner content and component properties", () => {
    const tagName = "h1";
    const expectedOutput = {
      content: "<h1>Welcome to my website</h1>",
      innerContent: "Welcome to my website",
      style: { fontWeight: "bold" },
    };
    expect(getTag(htmlString, tagName, componentList)).toEqual(expectedOutput);
  });
});

describe("getFirstComponent", () => {
  const componentList = {
    "tag-a": {
      fileName: "components/tag-a.html",
      fileContent: "<div><p>tag-a</p><slot-component></slot-component></div>",
    },
    "tag-b": {
      fileName: "components/tag-b.html",
      fileContent: "<div><p>tag-b</p><slot-component></slot-component></div>",
    },
    "tag-c": {
      fileName: "components/tag-c.html",
      fileContent: "<div><p>tag-c</p><slot-component></slot-component></div>",
    },
  } satisfies ComponentList;

  const htmlString = `<h1>Index</h1><tag-b></tag-b><tag-c></tag-c><my-footer></my-footer>`;

  it("should return an empty object when passed an empty string", () => {
    expect(getFirstComponent("", componentList)).toEqual({});
  });

  it("should return an empty object when no component is found in the string", () => {
    const htmlString = "<div><p>Hello World!</p></div>";
    expect(getFirstComponent(htmlString, componentList)).toEqual({});
  });

  it("should return the first component found in the string", () => {
    const expected = {
      name: "tag-b",
      index: 14,
      content: "<tag-b></tag-b>",
      innerContent: "",
      fileName: "components/tag-b.html",
      fileContent: "<div><p>tag-b</p><slot-component></slot-component></div>",
    };
    expect(getFirstComponent(htmlString, componentList)).toEqual(expected);
  });
});

describe("minifyHtml", () => {
  it("removes comments from HTML", () => {
    const htmlString = "<!-- comment --><div>content</div>";
    expect(minifyHtml(htmlString)).toEqual("<div>content</div>");
  });

  it("removes newlines and spaces from HTML, and removes extra spaces", () => {
    const htmlString = "<div>\n    \tcontent\n   \t</div>";
    expect(minifyHtml(htmlString)).toEqual("<div> content </div>");
  });

  it("removes comments, whitespace and newlines and puts script tags at the end of the HTML", () => {
    const htmlString = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Example</title>
        </head>
        <body>
          <h1>Hello, world!</h1>
          <p>This is an example page.</p>
          <!-- This is a comment -->
          <script>
            console.log("Hello, world!");
          </script>
          <script src="script.js"></script>
        </body>
      </html>
    `;
    const expected =
      '<!DOCTYPE html><html><head><title>Example</title></head><body><h1>Hello, world!</h1><p>This is an example page.</p></body></html>\n<script>\n            console.log("Hello, world!");\n          </script>\n<script src="script.js"></script>';

    const result = minifyHtml(htmlString);
    expect(result).toBe(expected);
  });

  it("handles an empty input string", () => {
    expect(minifyHtml("")).toEqual("");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Phase 2: Void / self-closing element tags
// ─────────────────────────────────────────────────────────────────────────────

describe("getTag – self-closing", () => {
  it("returns content and empty innerContent for <tag />", () => {
    expect(getTag("<my-nav />", "my-nav")).toEqual({
      content: "<my-nav />",
      innerContent: "",
    });
  });

  it("returns content and empty innerContent for <tag/> (no space)", () => {
    expect(getTag("<my-nav/>", "my-nav")).toEqual({
      content: "<my-nav/>",
      innerContent: "",
    });
  });

  it("returns content and empty innerContent for self-closing with attributes", () => {
    expect(getTag('<my-nav class="main" />', "my-nav")).toEqual({
      content: '<my-nav class="main" />',
      innerContent: "",
    });
  });

  it("still handles paired tags (regression)", () => {
    expect(getTag("<my-nav>inner</my-nav>", "my-nav")).toEqual({
      content: "<my-nav>inner</my-nav>",
      innerContent: "inner",
    });
  });
});

describe("replaceTag – self-closing", () => {
  it("replaces a self-closing tag", () => {
    expect(replaceTag("<div><my-nav /></div>", "my-nav", "<nav></nav>")).toBe(
      "<div><nav></nav></div>",
    );
  });

  it("replaces a self-closing tag without space before slash", () => {
    expect(replaceTag("<div><my-nav/></div>", "my-nav", "<nav></nav>")).toBe(
      "<div><nav></nav></div>",
    );
  });

  it("replaces self-closing with attributes", () => {
    expect(
      replaceTag('<div><my-nav class="x" /></div>', "my-nav", "<nav></nav>"),
    ).toBe("<div><nav></nav></div>");
  });

  it("still replaces paired tags (regression)", () => {
    expect(
      replaceTag(
        "<div><my-nav>inner</my-nav></div>",
        "my-nav",
        "<nav>inner</nav>",
      ),
    ).toBe("<div><nav>inner</nav></div>");
  });
});

describe("getFirstComponent – self-closing", () => {
  const componentList = {
    "my-nav": {
      fileName: "components/my-nav.html",
      fileContent: "<nav><ul><li>Home</li></ul></nav>",
    },
  };

  it("finds a self-closing component", () => {
    const result = getFirstComponent("<div><my-nav /></div>", componentList);
    expect(result.name).toBe("my-nav");
    expect(result.content).toBe("<my-nav />");
    expect(result.innerContent).toBe("");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Phase 3: Custom props
// ─────────────────────────────────────────────────────────────────────────────

describe("extractProps", () => {
  it("extracts a single prop", () => {
    expect(
      extractProps('<my-comp data-bascik-prop-title="Hello"></my-comp>'),
    ).toEqual({ title: "Hello" });
  });

  it("extracts multiple props", () => {
    expect(
      extractProps(
        '<my-comp data-bascik-prop-title="Hello" data-bascik-prop-href="/about"></my-comp>',
      ),
    ).toEqual({ title: "Hello", href: "/about" });
  });

  it("returns empty object when no props", () => {
    expect(extractProps("<my-comp></my-comp>")).toEqual({});
  });

  it("returns empty object for undefined input", () => {
    expect(extractProps(undefined)).toEqual({});
  });
});

describe("injectProps", () => {
  it("injects a prop value as element inner content", () => {
    const template = "<p data-bascik-prop-title></p>";
    expect(injectProps(template, { title: "Hello" })).toBe("<p>Hello</p>");
  });

  it("removes the data-bascik-prop attribute from the output", () => {
    const result = injectProps("<p data-bascik-prop-title></p>", {
      title: "Hi",
    });
    expect(result).not.toContain("data-bascik-prop-title");
  });

  it("preserves other attributes on the element", () => {
    const template = '<p class="lead" data-bascik-prop-title></p>';
    expect(injectProps(template, { title: "Hello" })).toBe(
      '<p class="lead">Hello</p>',
    );
  });

  it("injects multiple props into different elements", () => {
    const template =
      "<h1 data-bascik-prop-heading></h1><p data-bascik-prop-body></p>";
    expect(injectProps(template, { heading: "Title", body: "Content" })).toBe(
      "<h1>Title</h1><p>Content</p>",
    );
  });

  it("does not modify template when prop name has no matching element", () => {
    const template = "<p>static</p>";
    expect(injectProps(template, { title: "Hello" })).toBe("<p>static</p>");
  });

  it("strips unused data-bascik-prop-* markers when prop is not provided", () => {
    const template = "<span data-bascik-prop-file></span>";
    expect(injectProps(template, {})).toBe("<span></span>");
  });

  it("strips unused marker even when other props are injected", () => {
    const template =
      "<p data-bascik-prop-lang></p><span data-bascik-prop-file></span>";
    const result = injectProps(template, { lang: "html" });
    expect(result).toContain("<p>html</p>");
    expect(result).not.toContain("data-bascik-prop-file");
    expect(result).toContain("<span></span>");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Phase 4: Named slots
// ─────────────────────────────────────────────────────────────────────────────

describe("extractNamedSlotContent", () => {
  it("extracts a single named slot", () => {
    const inner = '<div data-bascik-slot="header"><h1>My Header</h1></div>';
    expect(extractNamedSlotContent(inner)).toEqual({
      header: "<h1>My Header</h1>",
    });
  });

  it("extracts multiple named slots", () => {
    const inner =
      '<div data-bascik-slot="header"><h1>H</h1></div>' +
      '<div data-bascik-slot="footer"><p>F</p></div>';
    expect(extractNamedSlotContent(inner)).toEqual({
      header: "<h1>H</h1>",
      footer: "<p>F</p>",
    });
  });

  it("returns empty object when no named slots", () => {
    expect(extractNamedSlotContent("<p>just content</p>")).toEqual({});
  });

  it("returns empty object for empty string", () => {
    expect(extractNamedSlotContent("")).toEqual({});
  });
});

describe("replaceNamedSlots", () => {
  it("replaces a named slot placeholder with provided content", () => {
    const template =
      '<footer><div data-bascik-slot="footer-links"></div></footer>';
    const slots = { "footer-links": "<a href='/'>Home</a>" };
    expect(replaceNamedSlots(template, slots)).toBe(
      "<footer><a href='/'>Home</a></footer>",
    );
  });

  it("removes an unfilled named slot placeholder", () => {
    const template =
      '<footer><div data-bascik-slot="footer-links"></div></footer>';
    expect(replaceNamedSlots(template, {})).toBe("<footer></footer>");
  });

  it("does not affect default slot-component", () => {
    const template =
      "<div><slot-component></slot-component>" +
      '<span data-bascik-slot="side"></span></div>';
    const slots = { side: "<p>sidebar</p>" };
    const result = replaceNamedSlots(template, slots);
    expect(result).toContain("<slot-component></slot-component>");
    expect(result).toContain("<p>sidebar</p>");
  });
});

describe("extractDefaultSlotContent", () => {
  it("strips named slot wrappers, keeping remaining content", () => {
    const inner =
      '<p>body</p><div data-bascik-slot="sidebar"><nav>nav</nav></div>';
    expect(extractDefaultSlotContent(inner)).toBe("<p>body</p>");
  });

  it("returns full content when there are no named slot wrappers", () => {
    expect(extractDefaultSlotContent("<p>content</p>")).toBe("<p>content</p>");
  });

  it("returns empty string for empty input", () => {
    expect(extractDefaultSlotContent("")).toBe("");
  });

  it("strips multiple named slot wrappers", () => {
    const inner =
      "<p>main</p>" +
      '<div data-bascik-slot="a"><span>a</span></div>' +
      '<div data-bascik-slot="b"><span>b</span></div>';
    expect(extractDefaultSlotContent(inner)).toBe("<p>main</p>");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// H: Named slot fallback content
// ─────────────────────────────────────────────────────────────────────────────

describe("replaceNamedSlots – fallback content", () => {
  it("renders fallback inner content when named slot is not provided", () => {
    const template =
      '<aside data-bascik-slot="sidebar"><p>Default sidebar</p></aside>';
    expect(replaceNamedSlots(template, {})).toBe("<p>Default sidebar</p>");
  });

  it("overrides fallback when named slot content is provided", () => {
    const template = '<aside data-bascik-slot="sidebar"><p>Default</p></aside>';
    expect(replaceNamedSlots(template, { sidebar: "<nav>Custom</nav>" })).toBe(
      "<nav>Custom</nav>",
    );
  });

  it("empty element placeholder still renders empty when not provided", () => {
    const template = '<div data-bascik-slot="footer"></div>';
    expect(replaceNamedSlots(template, {})).toBe("");
  });

  it("mixes filled and fallback slots in the same template", () => {
    const template =
      '<div data-bascik-slot="a"><p>fallback-a</p></div>' +
      '<div data-bascik-slot="b"><p>fallback-b</p></div>';
    const result = replaceNamedSlots(template, { a: "<h1>custom-a</h1>" });
    expect(result).toContain("<h1>custom-a</h1>");
    expect(result).toContain("<p>fallback-b</p>");
    expect(result).not.toContain("fallback-a");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// B: Attribute inheritance
// ─────────────────────────────────────────────────────────────────────────────

describe("extractInheritableAttributes", () => {
  it("extracts class attribute from usage tag", () => {
    expect(
      extractInheritableAttributes('<my-nav class="sticky"></my-nav>'),
    ).toEqual({ class: "sticky" });
  });

  it("extracts multiple inheritable attributes", () => {
    expect(
      extractInheritableAttributes(
        '<my-nav class="sticky" aria-label="nav" data-testid="main-nav"></my-nav>',
      ),
    ).toEqual({
      class: "sticky",
      "aria-label": "nav",
      "data-testid": "main-nav",
    });
  });

  it("excludes data-bascik-* attributes", () => {
    const result = extractInheritableAttributes(
      '<my-nav class="sticky" data-bascik-prop-title="Hi"></my-nav>',
    );
    expect(result).toEqual({ class: "sticky" });
    expect(result).not.toHaveProperty("data-bascik-prop-title");
  });

  it("returns empty object when no inheritable attributes", () => {
    expect(extractInheritableAttributes("<my-nav></my-nav>")).toEqual({});
  });

  it("handles self-closing tags", () => {
    expect(extractInheritableAttributes('<my-nav class="top" />')).toEqual({
      class: "top",
    });
  });
});

describe("mergeAttributesOntoRoot", () => {
  it("appends a class to the root element's existing class", () => {
    const html = '<nav class="scoped-nav"><a>link</a></nav>';
    const result = mergeAttributesOntoRoot(html, { class: "sticky" });
    expect(result).toContain('class="scoped-nav sticky"');
  });

  it("adds class attribute to root element that has none", () => {
    const html = "<nav><a>link</a></nav>";
    const result = mergeAttributesOntoRoot(html, { class: "sticky" });
    expect(result).toContain('class="sticky"');
  });

  it("adds aria-label to root element", () => {
    const html = '<nav class="nav"><a>link</a></nav>';
    const result = mergeAttributesOntoRoot(html, {
      "aria-label": "main navigation",
    });
    expect(result).toContain('aria-label="main navigation"');
  });

  it("does not override existing attributes on root element", () => {
    const html = '<nav id="main-nav"><a>link</a></nav>';
    const result = mergeAttributesOntoRoot(html, { id: "override" });
    // Should not override existing id
    expect(result).toContain('id="main-nav"');
    expect(result).not.toContain('id="override"');
  });

  it("returns unchanged html when attrs is empty", () => {
    const html = "<nav><a>link</a></nav>";
    expect(mergeAttributesOntoRoot(html, {})).toBe(html);
  });
});
