/**
 * Tests were generated by ChatGPT.
 * Test may have been modified by hand.
 */
import { describe, expect, it } from "vitest";
import type { ComponentList } from "./types.js";

import {
  replaceTag,
  getTagContents,
  getFirstComponent,
  getTag,
  extractScriptTags,
  minifyHtml,
  extractProps,
  injectProps,
  extractNamedSlotContent,
  replaceNamedSlots,
  extractDefaultSlotContent,
  extractInheritableAttributes,
  mergeAttributesOntoRoot,
} from "./components.js";

describe("extractScriptTags", () => {
  it("should extract one script tag", () => {
    const htmlString =
      "<html><body><script>alert('hello world')</script></body></html>";
    const expected = "<script>alert('hello world')</script>";
    expect(extractScriptTags(htmlString)).toEqual(expected);
  });

  it("should extract multiple script tags", () => {
    const htmlString = `
      <html>
        <body>
          <script>alert('hello world')</script>
          <script>console.log('goodbye world')</script>
        </body>
      </html>`;
    const expected = `<script>alert('hello world')</script>\n<script>console.log('goodbye world')</script>`;
    expect(extractScriptTags(htmlString)).toEqual(expected);
  });

  it("should not extract script tags that are commented out", () => {
    const htmlString = `
      <html>
        <body>
          <!-- <script>alert('hello world')</script> -->
          <script>console.log('goodbye world')</script>
        </body>
      </html>`;
    const expected = `<script>console.log('goodbye world')</script>`;
    expect(extractScriptTags(htmlString)).toEqual(expected);
  });

  it("should return an empty string if no script tags are found", () => {
    const htmlString = "<html><body><div>Hello world</div></body></html>";
    const expected = "";
    expect(extractScriptTags(htmlString)).toEqual(expected);
  });
});

describe("replaceTag", () => {
  it("replaces a single tag", () => {
    const input = "<div>before</div><span>replace me</span><div>after</div>";
    const output = "<div>before</div><p>new tag</p><div>after</div>";
    expect(replaceTag(input, "span", "<p>new tag</p>")).toEqual(output);
  });

  it("replaces only the first instance of a tag", () => {
    const input =
      "<div>before</div><span>replace me</span><span>do not replace me</span><div>after</div>";
    const output =
      "<div>before</div><p>new tag</p><span>do not replace me</span><div>after</div>";
    expect(replaceTag(input, "span", "<p>new tag</p>")).toEqual(output);
  });

  it("does not modify input when tag not found", () => {
    const input = "<div>before</div><p>do not replace me</p><div>after</div>";
    expect(replaceTag(input, "span", "<p>new tag</p>")).toEqual(input);
  });

  it("preserves tag attributes", () => {
    const input =
      '<div>before</div><span class="important">replace me</span><div>after</div>';
    const output =
      '<div>before</div><p class="important">new tag</p><div>after</div>';
    expect(
      replaceTag(input, "span", '<p class="important">new tag</p>'),
    ).toEqual(output);
  });

  it("is case-insensitive", () => {
    const input = "<div>before</div><SPAN>replace me</SPAN><div>after</div>";
    const output = "<div>before</div><p>new tag</p><div>after</div>";
    expect(replaceTag(input, "span", "<p>new tag</p>")).toEqual(output);
  });
});

describe("getTagContents", () => {
  it("gets contents of single tag", () => {
    const input = "<div>before</div><span>get me</span><div>after</div>";
    const output = { content: "<span>get me</span>", innerContent: "get me" };
    expect(getTagContents(input, "span")).toEqual(output);
  });

  it("gets contents of first matching tag", () => {
    const input =
      "<div>before</div><span>get me</span><span>not me</span><div>after</div>";
    const output = { content: "<span>get me</span>", innerContent: "get me" };
    expect(getTagContents(input, "span")).toEqual(output);
  });

  it("returns empty object when tag not found", () => {
    const input = "<div>before</div><p>do not get me</p><div>after</div>";
    const output = {};
    expect(getTagContents(input, "span")).toEqual(output);
  });

  it("preserves tag attributes", () => {
    const input =
      '<div>before</div><span class="important">get me</span><div>after</div>';
    const output = {
      content: '<span class="important">get me</span>',
      innerContent: "get me",
    };
    expect(getTagContents(input, "span")).toEqual(output);
  });

  it("is case-insensitive", () => {
    const input = "<div>before</div><SPAN>get me</SPAN><div>after</div>";
    const output = { content: "<SPAN>get me</SPAN>", innerContent: "get me" };
    expect(getTagContents(input, "span")).toEqual(output);
  });
});

describe("getTag", () => {
  const htmlString = `
    <div class="container">
      <h1>Welcome to my website</h1>
      <p>This is a test paragraph</p>
    </div>
  `;
  // Test component list with extra metadata — cast because these have non-standard properties
  const componentList = {
    div: { className: "container" },
    h1: { style: { fontWeight: "bold" } },
  } as unknown as ComponentList;

  it("returns content and inner content of tag", () => {
    const tagName = "p";
    const expectedOutput = {
      content: "<p>This is a test paragraph</p>",
      innerContent: "This is a test paragraph",
    };
    expect(getTag(htmlString, tagName)).toEqual(expectedOutput);
  });

  it("returns empty object when tag not found", () => {
    const tagName = "span";
    expect(getTag(htmlString, tagName)).toEqual({});
  });

  it("returns content, inner content and component properties", () => {
    const tagName = "h1";
    const expectedOutput = {
      content: "<h1>Welcome to my website</h1>",
      innerContent: "Welcome to my website",
      style: { fontWeight: "bold" },
    };
    expect(getTag(htmlString, tagName, componentList)).toEqual(expectedOutput);
  });
});

describe("getFirstComponent", () => {
  const componentList = {
    "tag-a": {
      fileName: "components/tag-a.html",
      fileContent: "<div><p>tag-a</p><div data-bascik-slot></div></div>",
    },
    "tag-b": {
      fileName: "components/tag-b.html",
      fileContent: "<div><p>tag-b</p><div data-bascik-slot></div></div>",
    },
    "tag-c": {
      fileName: "components/tag-c.html",
      fileContent: "<div><p>tag-c</p><div data-bascik-slot></div></div>",
    },
  } satisfies ComponentList;

  const htmlString = `<h1>Index</h1><tag-b></tag-b><tag-c></tag-c><my-footer></my-footer>`;

  it("should return an empty object when passed an empty string", () => {
    expect(getFirstComponent("", componentList)).toEqual({});
  });

  it("should return an empty object when no component is found in the string", () => {
    const htmlString = "<div><p>Hello World!</p></div>";
    expect(getFirstComponent(htmlString, componentList)).toEqual({});
  });

  it("should return the first component found in the string", () => {
    const expected = {
      name: "tag-b",
      index: 14,
      content: "<tag-b></tag-b>",
      innerContent: "",
      fileName: "components/tag-b.html",
      fileContent: "<div><p>tag-b</p><div data-bascik-slot></div></div>",
    };
    expect(getFirstComponent(htmlString, componentList)).toEqual(expected);
  });

  describe("getFirstComponent – missing from list", () => {
    it("should return an object with name but no fileContent if matched but not in list (edge case)", () => {
      // This shouldn't happen normally because the regex is built from keys
      const html = "<unknown-comp></unknown-comp>";
      const componentList: ComponentList = {};
      // Mock the regex to include unknown-comp
      const result = getTag(html, "unknown-comp", componentList);
      expect(result.content).toBeDefined();
      expect(result.fileContent).toBeUndefined();
    });
  });

  describe("getFirstComponent – dangling closing tag", () => {
    it("should not match a closing tag if it appears without an opening tag", () => {
      const html = "<div></code-block></div>";
      const componentList: ComponentList = {
        "code-block": { fileContent: "<div></div>" },
      };
      const result = getFirstComponent(html, componentList);
      expect(result.name).toBeUndefined();
    });
  });
});

describe("minifyHtml", () => {
  it("removes comments from HTML", () => {
    const htmlString = "<!-- comment --><div>content</div>";
    expect(minifyHtml(htmlString)).toEqual("<div>content</div>");
  });

  it("removes newlines and spaces from HTML, and removes extra spaces", () => {
    const htmlString = "<div>\n    \tcontent\n   \t</div>";
    expect(minifyHtml(htmlString)).toEqual("<div> content </div>");
  });

  it("preserves content of <pre> elements verbatim", () => {
    const htmlString =
      "<div>\n  <pre><code>\n    line1\n    line2\n  </code></pre>\n</div>";
    const result = minifyHtml(htmlString);
    expect(result).toBe(
      "<div><pre><code>\n    line1\n    line2\n  </code></pre></div>",
    );
  });

  it("preserves content of <pre> elements with attributes", () => {
    const htmlString = '<div><pre class="code-block">  indented\ncode\n</pre></div>';
    const result = minifyHtml(htmlString);
    expect(result).toBe('<div><pre class="code-block">  indented\ncode\n</pre></div>');
  });

  it("removes comments, whitespace and newlines and puts script tags at the end of the HTML", () => {
    const htmlString = `
      <!DOCTYPE html>
      <html>
        <head>
          <title>Example</title>
        </head>
        <body>
          <h1>Hello, world!</h1>
          <p>This is an example page.</p>
          <!-- This is a comment -->
          <script>
            console.log("Hello, world!");
          </script>
          <script src="script.js"></script>
        </body>
      </html>
    `;
    const expected =
      '<!DOCTYPE html><html><head><title>Example</title></head><body><h1>Hello, world!</h1><p>This is an example page.</p></body></html>\n<script>\n            console.log("Hello, world!");\n          </script>\n<script src="script.js"></script>';

    const result = minifyHtml(htmlString);
    expect(result).toBe(expected);
  });

  it("handles an empty input string", () => {
    expect(minifyHtml("")).toEqual("");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Phase 2: Void / self-closing element tags
// ─────────────────────────────────────────────────────────────────────────────

describe("getTag – self-closing", () => {
  it("returns content and empty innerContent for <tag />", () => {
    expect(getTag("<my-nav />", "my-nav")).toEqual({
      content: "<my-nav />",
      innerContent: "",
    });
  });

  it("returns content and empty innerContent for <tag/> (no space)", () => {
    expect(getTag("<my-nav/>", "my-nav")).toEqual({
      content: "<my-nav/>",
      innerContent: "",
    });
  });

  it("returns content and empty innerContent for self-closing with attributes", () => {
    expect(getTag('<my-nav class="main" />', "my-nav")).toEqual({
      content: '<my-nav class="main" />',
      innerContent: "",
    });
  });

  it("still handles paired tags (regression)", () => {
    expect(getTag("<my-nav>inner</my-nav>", "my-nav")).toEqual({
      content: "<my-nav>inner</my-nav>",
      innerContent: "inner",
    });
  });
});

describe("replaceTag – self-closing", () => {
  it("replaces a self-closing tag", () => {
    expect(replaceTag("<div><my-nav /></div>", "my-nav", "<nav></nav>")).toBe(
      "<div><nav></nav></div>",
    );
  });

  it("replaces a self-closing tag without space before slash", () => {
    expect(replaceTag("<div><my-nav/></div>", "my-nav", "<nav></nav>")).toBe(
      "<div><nav></nav></div>",
    );
  });

  it("replaces self-closing with attributes", () => {
    expect(
      replaceTag('<div><my-nav class="x" /></div>', "my-nav", "<nav></nav>"),
    ).toBe("<div><nav></nav></div>");
  });

  it("still replaces paired tags (regression)", () => {
    expect(
      replaceTag(
        "<div><my-nav>inner</my-nav></div>",
        "my-nav",
        "<nav>inner</nav>",
      ),
    ).toBe("<div><nav>inner</nav></div>");
  });
});

describe("getFirstComponent – self-closing", () => {
  const componentList = {
    "my-nav": {
      fileName: "components/my-nav.html",
      fileContent: "<nav><ul><li>Home</li></ul></nav>",
    },
  };

  it("finds a self-closing component", () => {
    const result = getFirstComponent("<div><my-nav /></div>", componentList);
    expect(result.name).toBe("my-nav");
    expect(result.content).toBe("<my-nav />");
    expect(result.innerContent).toBe("");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Phase 3: Custom props
// ─────────────────────────────────────────────────────────────────────────────

describe("extractProps", () => {
  it("extracts a single prop", () => {
    expect(
      extractProps('<my-comp data-bascik-prop-title="Hello"></my-comp>'),
    ).toEqual({ title: "Hello" });
  });

  it("extracts multiple props", () => {
    expect(
      extractProps(
        '<my-comp data-bascik-prop-title="Hello" data-bascik-prop-href="/about"></my-comp>',
      ),
    ).toEqual({ title: "Hello", href: "/about" });
  });

  it("returns empty object when no props", () => {
    expect(extractProps("<my-comp></my-comp>")).toEqual({});
  });

  it("returns empty object for undefined input", () => {
    expect(extractProps(undefined)).toEqual({});
  });
});

describe("injectProps", () => {
  it("injects a prop value as element inner content", () => {
    const template = "<p data-bascik-prop-title></p>";
    expect(injectProps(template, { title: "Hello" })).toBe("<p>Hello</p>");
  });

  it("removes the data-bascik-prop attribute from the output", () => {
    const result = injectProps("<p data-bascik-prop-title></p>", {
      title: "Hi",
    });
    expect(result).not.toContain("data-bascik-prop-title");
  });

  it("preserves other attributes on the element", () => {
    const template = '<p class="lead" data-bascik-prop-title></p>';
    expect(injectProps(template, { title: "Hello" })).toBe(
      '<p class="lead">Hello</p>',
    );
  });

  it("injects multiple props into different elements", () => {
    const template =
      "<h1 data-bascik-prop-heading></h1><p data-bascik-prop-body></p>";
    expect(injectProps(template, { heading: "Title", body: "Content" })).toBe(
      "<h1>Title</h1><p>Content</p>",
    );
  });

  it("does not modify template when prop name has no matching element", () => {
    const template = "<p>static</p>";
    expect(injectProps(template, { title: "Hello" })).toBe("<p>static</p>");
  });

  it("strips unused data-bascik-prop-* markers when prop is not provided", () => {
    const template = "<span data-bascik-prop-file></span>";
    expect(injectProps(template, {})).toBe("<span></span>");
  });

  it("strips unused marker even when other props are injected", () => {
    const template =
      "<p data-bascik-prop-lang></p><span data-bascik-prop-file></span>";
    const result = injectProps(template, { lang: "html" });
    expect(result).toContain("<p>html</p>");
    expect(result).not.toContain("data-bascik-prop-file");
    expect(result).toContain("<span></span>");
  });

  it("handles undefined fileContent gracefully", () => {
    expect(injectProps(undefined, {})).toBe("");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Phase 4: Named slots
// ─────────────────────────────────────────────────────────────────────────────

describe("extractNamedSlotContent", () => {
  it("extracts a single named slot", () => {
    const inner = '<div data-bascik-slot="header"><h1>My Header</h1></div>';
    expect(extractNamedSlotContent(inner)).toEqual({
      header: "<h1>My Header</h1>",
    });
  });

  it("extracts multiple named slots", () => {
    const inner =
      '<div data-bascik-slot="header"><h1>H</h1></div>' +
      '<div data-bascik-slot="footer"><p>F</p></div>';
    expect(extractNamedSlotContent(inner)).toEqual({
      header: "<h1>H</h1>",
      footer: "<p>F</p>",
    });
  });

  it("returns empty object when no named slots", () => {
    expect(extractNamedSlotContent("<p>just content</p>")).toEqual({});
  });

  it("returns empty object for empty string", () => {
    expect(extractNamedSlotContent("")).toEqual({});
  });

  it("handles nested same-tag elements inside slot wrapper", () => {
    // The slot wrapper is a <div>. The content also contains a <div>.
    // The regex must close at the OUTER </div>, not the first inner one.
    const inner =
      '<div data-bascik-slot="example">' +
      "<p>Before</p><div style=\"nested\"><span>Inner</span></div><p>After</p>" +
      "</div>";
    expect(extractNamedSlotContent(inner)).toEqual({
      example: "<p>Before</p><div style=\"nested\"><span>Inner</span></div><p>After</p>",
    });
  });

  it("handles deeply nested same-tag elements", () => {
    const inner =
      '<div data-bascik-slot="x">' +
      "<div><div><p>deep</p></div></div>" +
      "</div>" +
      '<div data-bascik-slot="y"><span>y</span></div>';
    expect(extractNamedSlotContent(inner)).toEqual({
      x: "<div><div><p>deep</p></div></div>",
      y: "<span>y</span>",
    });
  });
});

describe("replaceNamedSlots", () => {
  it("replaces a named slot placeholder with provided content", () => {
    const template =
      '<footer><div data-bascik-slot="footer-links"></div></footer>';
    const slots = { "footer-links": "<a href='/'>Home</a>" };
    expect(replaceNamedSlots(template, slots)).toBe(
      "<footer><a href='/'>Home</a></footer>",
    );
  });

  it("removes an unfilled named slot placeholder", () => {
    const template =
      '<footer><div data-bascik-slot="footer-links"></div></footer>';
    expect(replaceNamedSlots(template, {})).toBe("<footer></footer>");
  });

  it("does not affect default data-bascik-slot", () => {
    const template =
      "<div><div data-bascik-slot></div>" +
      '<span data-bascik-slot="side"></span></div>';
    const slots = { side: "<p>sidebar</p>" };
    const result = replaceNamedSlots(template, slots);
    expect(result).toContain("<div data-bascik-slot></div>");
    expect(result).toContain("<p>sidebar</p>");
  });
});

describe("extractDefaultSlotContent", () => {
  it("strips named slot wrappers, keeping remaining content", () => {
    const inner =
      '<p>body</p><div data-bascik-slot="sidebar"><nav>nav</nav></div>';
    expect(extractDefaultSlotContent(inner)).toBe("<p>body</p>");
  });

  it("returns full content when there are no named slot wrappers", () => {
    expect(extractDefaultSlotContent("<p>content</p>")).toBe("<p>content</p>");
  });

  it("returns empty string for empty input", () => {
    expect(extractDefaultSlotContent("")).toBe("");
  });

  it("strips multiple named slot wrappers", () => {
    const inner =
      "<p>main</p>" +
      '<div data-bascik-slot="a"><span>a</span></div>' +
      '<div data-bascik-slot="b"><span>b</span></div>';
    expect(extractDefaultSlotContent(inner)).toBe("<p>main</p>");
  });

  it("strips named slot wrapper containing nested same-tag elements", () => {
    // Slot wrapper is <div>. Content has inner <div>s — must strip whole wrapper.
    const inner =
      "<p>default</p>" +
      '<div data-bascik-slot="side"><div style="inner"><span>s</span></div></div>';
    expect(extractDefaultSlotContent(inner)).toBe("<p>default</p>");
  });

  it("trims surrounding whitespace from slot content", () => {
    expect(extractDefaultSlotContent("\n  code here\n")).toBe("code here");
  });

  it("trims whitespace left after named slot wrappers are removed", () => {
    const inner =
      "\n  <p>main</p>\n  " +
      '<div data-bascik-slot="a"><span>a</span></div>' +
      "\n";
    expect(extractDefaultSlotContent(inner)).toBe("<p>main</p>");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// H: Named slot fallback content
// ─────────────────────────────────────────────────────────────────────────────

describe("replaceNamedSlots – fallback content", () => {
  it("renders fallback inner content when named slot is not provided", () => {
    const template =
      '<aside data-bascik-slot="sidebar"><p>Default sidebar</p></aside>';
    expect(replaceNamedSlots(template, {})).toBe("<p>Default sidebar</p>");
  });

  it("overrides fallback when named slot content is provided", () => {
    const template = '<aside data-bascik-slot="sidebar"><p>Default</p></aside>';
    expect(replaceNamedSlots(template, { sidebar: "<nav>Custom</nav>" })).toBe(
      "<nav>Custom</nav>",
    );
  });

  it("empty element placeholder still renders empty when not provided", () => {
    const template = '<div data-bascik-slot="footer"></div>';
    expect(replaceNamedSlots(template, {})).toBe("");
  });

  it("mixes filled and fallback slots in the same template", () => {
    const template =
      '<div data-bascik-slot="a"><p>fallback-a</p></div>' +
      '<div data-bascik-slot="b"><p>fallback-b</p></div>';
    const result = replaceNamedSlots(template, { a: "<h1>custom-a</h1>" });
    expect(result).toContain("<h1>custom-a</h1>");
    expect(result).toContain("<p>fallback-b</p>");
    expect(result).not.toContain("fallback-a");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// B: Attribute inheritance
// ─────────────────────────────────────────────────────────────────────────────

describe("extractInheritableAttributes", () => {
  it("extracts class attribute from usage tag", () => {
    expect(
      extractInheritableAttributes('<my-nav class="sticky"></my-nav>'),
    ).toEqual({ class: "sticky" });
  });

  it("extracts multiple inheritable attributes", () => {
    expect(
      extractInheritableAttributes(
        '<my-nav class="sticky" aria-label="nav" data-testid="main-nav"></my-nav>',
      ),
    ).toEqual({
      class: "sticky",
      "aria-label": "nav",
      "data-testid": "main-nav",
    });
  });

  it("excludes data-bascik-* attributes", () => {
    const result = extractInheritableAttributes(
      '<my-nav class="sticky" data-bascik-prop-title="Hi"></my-nav>',
    );
    expect(result).toEqual({ class: "sticky" });
    expect(result).not.toHaveProperty("data-bascik-prop-title");
  });

  it("returns empty object when no inheritable attributes", () => {
    expect(extractInheritableAttributes("<my-nav></my-nav>")).toEqual({});
  });

  it("handles self-closing tags", () => {
    expect(extractInheritableAttributes('<my-nav class="top" />')).toEqual({
      class: "top",
    });
  });
});

describe("mergeAttributesOntoRoot", () => {
  it("appends a class to the root element's existing class", () => {
    const html = '<nav class="scoped-nav"><a>link</a></nav>';
    const result = mergeAttributesOntoRoot(html, { class: "sticky" });
    expect(result).toContain('class="scoped-nav sticky"');
  });

  it("adds class attribute to root element that has none", () => {
    const html = "<nav><a>link</a></nav>";
    const result = mergeAttributesOntoRoot(html, { class: "sticky" });
    expect(result).toContain('class="sticky"');
  });

  it("adds aria-label to root element", () => {
    const html = '<nav class="nav"><a>link</a></nav>';
    const result = mergeAttributesOntoRoot(html, {
      "aria-label": "main navigation",
    });
    expect(result).toContain('aria-label="main navigation"');
  });

  it("does not override existing attributes on root element", () => {
    const html = '<nav id="main-nav"><a>link</a></nav>';
    const result = mergeAttributesOntoRoot(html, { id: "override" });
    // Should not override existing id
    expect(result).toContain('id="main-nav"');
    expect(result).not.toContain('id="override"');
  });

  it("returns unchanged html when attrs is empty", () => {
    const html = "<nav><a>link</a></nav>";
    expect(mergeAttributesOntoRoot(html, {})).toBe(html);
  });
});

describe("getTag – multiline and complex attributes", () => {
  it("handles a component with multiline content and attributes", () => {
    const html = `
      <code-block 
        data-bascik-prop-lang="html" 
        data-bascik-prop-file="src/pages/index.html">
        &lt;div&gt;
          Hello
        &lt;/div&gt;
      </code-block>`;
    const result = getTag(html, "code-block");
    expect(result.content).toBeDefined();
    expect(result.innerContent).toContain("&lt;div&gt;");
  });

  it("handles self-closing with multiline attributes", () => {
    const html = `
      <my-comp 
        attr="val"
        class="foo" 
      />`;
    const result = getTag(html, "my-comp");
    expect(result.content).toBeDefined();
    expect(result.content).toContain('class="foo"');
  });
});

describe("getFirstComponent – regression with multiline", () => {
  it("finds a component even if it has newlines in the tag", () => {
    const html = `
      <div>
        <code-block 
          data-bascik-prop-lang="js">
          console.log(1);
        </code-block>
      </div>`;
    const componentList: ComponentList = {
      "code-block": { fileContent: "<div></div>" },
    };
    const result = getFirstComponent(html, componentList);
    expect(result.name).toBe("code-block");
    expect(result.content).toBeDefined();
  });

  it("handles code-block with multiline escaped content and attributes", () => {
    const html = `
      <code-block data-bascik-prop-lang="html">
        &lt;feature-card
        data-bascik-prop-label="Example"
        data-bascik-prop-title="Named Slots"
        data-bascik-prop-desc="..."&gt;
        &lt;!-- content for default slot --&gt;
        &lt;div style="padding-top:12px;..."&gt;
        &lt;button class="btn btn-primary"&gt;Read More&lt;/button&gt;
        &lt;/div&gt;
        &lt;/feature-card&gt;</code-block>`;
    const componentList: ComponentList = {
      "code-block": { fileContent: "<div><div data-bascik-slot></div></div>" },
    };
    const result = getTag(html, "code-block", componentList);
    expect(result.fileContent).toBeDefined();
    expect(result.innerContent).toContain("&lt;feature-card");
    expect(result.innerContent).toContain("&lt;/feature-card&gt;");
  });
});

describe("replaceTag – regression with multiline", () => {
  it("replaces a multiline tag with provided content", () => {
    const template =
      '<footer><div data-bascik-slot="footer-links"></div></footer>';
    const slots = { "footer-links": "<a href='/'>Home</a>" };
    expect(replaceNamedSlots(template, slots)).toBe(
      "<footer><a href='/'>Home</a></footer>",
    );
  });

  it("removes an unfilled named slot placeholder", () => {
    const template =
      '<footer><div data-bascik-slot="footer-links"></div></footer>';
    expect(replaceNamedSlots(template, {})).toBe("<footer></footer>");
  });

  it("does not affect default data-bascik-slot", () => {
    const template =
      "<div><div data-bascik-slot></div>" +
      '<span data-bascik-slot="side"></span></div>';
    const slots = { side: "<p>sidebar</p>" };
    const result = replaceNamedSlots(template, slots);
    expect(result).toContain("<div data-bascik-slot></div>");
    expect(result).toContain("<p>sidebar</p>");
  });
});

describe("getTag – case sensitivity bug repro", () => {
  it("returns fileContent even if the tag in HTML is uppercase", () => {
    const html = "<MY-COMP></MY-COMP>";
    const componentList: ComponentList = {
      "my-comp": { fileContent: "<div></div>" },
    };
    const result = getTag(html, "MY-COMP", componentList);
    // This will fail currently because componentList["MY-COMP"] is undefined
    expect(result.fileContent).toBe("<div></div>");
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Bug 1: nested same-name component pairing
// ─────────────────────────────────────────────────────────────────────────────

describe("getTag – nested same-name tags", () => {
  it("pairs with the balanced close tag, not the first inner close tag", () => {
    const html =
      "<my-list><li>one</li><my-list><li>nested</li></my-list><li>two</li></my-list>";
    const result = getTag(html, "my-list");
    expect(result.content).toBe(html);
    expect(result.innerContent).toBe(
      "<li>one</li><my-list><li>nested</li></my-list><li>two</li>",
    );
  });

  it("handles deeply nested same-name tags", () => {
    const html = "<my-list>a<my-list>b<my-list>c</my-list>d</my-list>e</my-list>";
    const result = getTag(html, "my-list");
    expect(result.content).toBe(html);
    expect(result.innerContent).toBe(
      "a<my-list>b<my-list>c</my-list>d</my-list>e",
    );
  });

  it("returns the first balanced element when siblings follow", () => {
    const html =
      "<my-list><my-list>x</my-list></my-list><my-list>second</my-list>";
    const result = getTag(html, "my-list");
    expect(result.content).toBe("<my-list><my-list>x</my-list></my-list>");
    expect(result.innerContent).toBe("<my-list>x</my-list>");
  });

  it("still pairs correctly when attributes contain >", () => {
    const html =
      '<my-comp title="a > b"><span>body</span></my-comp>';
    const result = getTag(html, "my-comp");
    expect(result.content).toBe(html);
    expect(result.innerContent).toBe("<span>body</span>");
  });

  it("keeps non-nested behavior identical (regression)", () => {
    const html = "<div>before</div><my-comp>inner</my-comp><div>after</div>";
    const result = getTag(html, "my-comp");
    expect(result.content).toBe("<my-comp>inner</my-comp>");
    expect(result.innerContent).toBe("inner");
  });
});

describe("replaceTag – nested same-name tags", () => {
  it("replaces the whole balanced element, not just up to the inner close", () => {
    const html =
      "<div>before</div><my-list><li>one</li><my-list><li>nested</li></my-list><li>two</li></my-list><div>after</div>";
    const result = replaceTag(html, "my-list", "<ul>transpiled</ul>");
    expect(result).toBe(
      "<div>before</div><ul>transpiled</ul><div>after</div>",
    );
  });

  it("does not treat $ in the replacement as a back-reference", () => {
    const html = "<my-list><my-list>x</my-list></my-list>";
    const result = replaceTag(html, "my-list", "<ul>$1 $& $`</ul>");
    expect(result).toBe("<ul>$1 $& $`</ul>");
  });

  it("keeps replacing only the first instance with nesting", () => {
    const html =
      "<my-list><my-list>x</my-list></my-list><my-list>second</my-list>";
    const result = replaceTag(html, "my-list", "<ul>done</ul>");
    expect(result).toBe("<ul>done</ul><my-list>second</my-list>");
  });

  it("still replaces paired tags with attributes (regression)", () => {
    expect(
      replaceTag(
        '<div><my-nav class="x">inner</my-nav></div>',
        "my-nav",
        "<nav>inner</nav>",
      ),
    ).toBe('<div><nav>inner</nav></div>');
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Bug 2: quote-aware props & attribute scanning
// ─────────────────────────────────────────────────────────────────────────────

describe("extractProps – single-quoted values", () => {
  it("extracts a single-quoted prop value", () => {
    expect(
      extractProps("<my-comp data-bascik-prop-title='Hi'></my-comp>"),
    ).toEqual({ title: "Hi" });
  });

  it("extracts mixed single- and double-quoted prop values", () => {
    expect(
      extractProps(
        `<my-comp data-bascik-prop-title='Hi' data-bascik-prop-href="/about"></my-comp>`,
      ),
    ).toEqual({ title: "Hi", href: "/about" });
  });

  it("extracts a single-quoted value containing double quotes", () => {
    expect(
      extractProps(
        `<my-comp data-bascik-prop-title='say "hi"'></my-comp>`,
      ),
    ).toEqual({ title: 'say "hi"' });
  });
});

describe("extractInheritableAttributes – quote-aware scanning", () => {
  it("does not end the open tag at a > inside a double-quoted value", () => {
    expect(
      extractInheritableAttributes(
        '<my-comp title="a > b" class="sticky"></my-comp>',
      ),
    ).toEqual({ title: "a > b", class: "sticky" });
  });

  it("does not end the open tag at a > inside a single-quoted value", () => {
    expect(
      extractInheritableAttributes(
        "<my-comp title='a > b' class=\"sticky\"></my-comp>",
      ),
    ).toEqual({ title: "a > b", class: "sticky" });
  });

  it("accepts single-quoted attribute values", () => {
    expect(
      extractInheritableAttributes("<my-nav class='sticky'></my-nav>"),
    ).toEqual({ class: "sticky" });
  });

  it("keeps extracting attributes after one with > in its value", () => {
    const result = extractInheritableAttributes(
      '<my-nav data-tip="1 > 0" aria-label="nav" id="top"></my-nav>',
    );
    expect(result).toEqual({
      "data-tip": "1 > 0",
      "aria-label": "nav",
      id: "top",
    });
  });
});

describe("injectProps – quote-aware scanning", () => {
  it("matches the marker element when a previous attribute value contains >", () => {
    const template = '<p title="a > b" data-bascik-prop-title></p>';
    expect(injectProps(template, { title: "Hi" })).toBe(
      '<p title="a > b">Hi</p>',
    );
  });

  it("matches the marker element when a following attribute value contains >", () => {
    const template = '<p data-bascik-prop-title data-tip="1 > 0"></p>';
    expect(injectProps(template, { title: "Hi" })).toBe(
      '<p data-tip="1 > 0">Hi</p>',
    );
  });

  it("supports single-quoted attribute values on the marker element", () => {
    const template = "<p class='lead' data-bascik-prop-title></p>";
    expect(injectProps(template, { title: "Hello" })).toBe(
      "<p class='lead'>Hello</p>",
    );
  });

  it("handles a valued single-quoted marker attribute", () => {
    const template = "<p data-bascik-prop-title='featured'></p>";
    expect(injectProps(template, { title: "Hi" })).toBe("<p>Hi</p>");
  });
});

// Regression: the quote-aware ATTR_VALUE scan previously used
// `(?:"[^"]*"|'[^']*'|[^>])*`, whose ambiguous alternation (`[^>]` also
// matches quote characters) backtracked exponentially when the rest of the
// pattern could not match.  A component whose prop-marker element had no
// balancing close tag (e.g. the marker's `<span>` was consumed but the
// closing `</span>` never followed in the scanned string) would hang the
// build for minutes.  These tests must complete in milliseconds.
describe("injectProps – does not hang on unbalanced markup", () => {
  it("returns quickly when a balanced marker is followed by a long unclosed tag", () => {
    // The balanced <span> is injected; the trailing unclosed <div class="…">
    // (no `>`) must not send the regex into exponential backtracking.
    const template =
      '<span data-bascik-prop-lang>x</span><div class="' + "a".repeat(4000) + '">';
    expect(injectProps(template, { lang: "js" })).toBe(
      '<span>js</span><div class="' + "a".repeat(4000) + '">',
    );
  });

  it("returns quickly when the marker element has no closing tag", () => {
    // Marker <span> is opened but `</span>` never appears before the string
    // ends.  injectProps only rewrites balanced marker elements, so here the
    // value is intentionally NOT injected; the leftover valueless marker is
    // stripped by the trailing cleanup pass, leaving the inner content intact.
    const rest = '<div class="y">"quoted"</div>'.repeat(500);
    const template = '<span data-bascik-prop-lang>' + rest;
    expect(injectProps(template, { lang: "js" })).toBe("<span>" + rest);
  });

  it("returns quickly when no element carries the marker", () => {
    const template = "<p>static</p>" + '<div class="x">"quoted"</div>'.repeat(500);
    expect(injectProps(template, { title: "Hi" })).toBe(template);
  });
});

describe("extractInheritableAttributes – does not hang on unbalanced markup", () => {
  it("returns quickly when the opening tag is never closed", () => {
    const content = "<div " + 'a="b" '.repeat(5000); // no `>` anywhere
    expect(extractInheritableAttributes(content)).toEqual({});
  });
});

describe("recursivelyTranspile – complex regression", () => {
  it("finds a component even if it has newlines in the tag", () => {
    const html = `
      <div>
        <code-block 
          data-bascik-prop-lang="js">
          console.log(1);
        </code-block>
      </div>`;
    const componentList: ComponentList = {
      "code-block": { fileContent: "<div></div>" },
    };
    const result = getFirstComponent(html, componentList);
    expect(result.name).toBe("code-block");
    expect(result.content).toBeDefined();
  });
});

// ─────────────────────────────────────────────────────────────────────────────
// Property-based fuzzing
// ─────────────────────────────────────────────────────────────────────────────

import fc from "fast-check";

describe("getTag / getFirstComponent / replaceTag – property-based fuzzing", () => {
  const compNameArb = fc.constantFrom(
    "my-card",
    "site-nav",
    "feature-row",
    "alert-box",
    "user-profile",
  );

  const innerContentArb = fc.constantFrom(
    "",
    "<p>hello</p>",
    "<span id=\"x\">hi</span>",
    "<div class=\"wrap\"><p>nested</p></div>",
    "<!-- comment -->",
    "<br /><img src=\"x.png\" />",
    "<p>line 1</p>\n<p>line 2</p>",
    "<p data-bascik-slot>fallback</p>",
  );

  const attrArb = fc.constantFrom(
    "",
    ' class="highlight"',
    ' id="main"',
    ' data-bascik-prop-title="Hello"',
    ' class="a b" id="root"',
  );

  it("getTag does not throw on generated HTML and does not return sentinels", () => {
    fc.assert(
      fc.property(compNameArb, innerContentArb, attrArb, (name, inner, attrs) => {
        const html = `<${name}${attrs}>${inner}</${name}>`;
        expect(() => getTag(html, name)).not.toThrow();
        const result = getTag(html, name);
        expect(typeof (result.content ?? "")).toBe("string");
        expect(result.content ?? "").not.toContain("\x00");
      }),
      { numRuns: 150 },
    );
  });

  it("replaceTag does not throw and output contains replacement", () => {
    fc.assert(
      fc.property(compNameArb, innerContentArb, attrArb, (name, inner, attrs) => {
        const original = `<${name}${attrs}>${inner}</${name}>`;
        const replacement = `<div>replaced</div>`;
        expect(() => replaceTag(original, name, replacement)).not.toThrow();
        const result = replaceTag(original, name, replacement);
        expect(result).toContain("replaced");
        expect(result).not.toContain(`<${name}`);
      }),
      { numRuns: 150 },
    );
  });

  it("getFirstComponent returns the known component name or an empty object", () => {
    fc.assert(
      fc.property(compNameArb, innerContentArb, attrArb, (name, inner, attrs) => {
        const html = `<section><${name}${attrs}>${inner}</${name}></section>`;
        const componentList: ComponentList = {
          [name]: { fileName: `components/${name}.html`, fileContent: `<div>${inner}</div>` },
        };
        expect(() => getFirstComponent(html, componentList)).not.toThrow();
        const result = getFirstComponent(html, componentList);
        if (result.name) expect(result.name).toBe(name);
      }),
      { numRuns: 150 },
    );
  });

  it("replaceTag with $-containing replacement does not throw or lose content", () => {
    // Regression target: String.replace treats $1, $& etc as capture-group refs.
    fc.assert(
      fc.property(compNameArb, fc.constantFrom("$1", "$&", "$'", "$$", "$`"), (name, dollarStr) => {
        const original = `<${name}>inner</${name}>`;
        const replacement = `<p>${dollarStr}</p>`;
        expect(() => replaceTag(original, name, replacement)).not.toThrow();
        const result = replaceTag(original, name, replacement);
        expect(result).toContain(dollarStr);
      }),
      { numRuns: 50 },
    );
  });
});

describe("injectProps – adversarial prop values", () => {
  it("does not throw and prop values with special chars are injected verbatim", () => {
    const propValueArb = fc.constantFrom(
      "Hello world",
      "It's a test",
      "<em>bold</em>",
      "$1 and $& and $'",
      "100% done",
      "A \u003e B",
      "line1\nline2",
      "",
      "bascik__comp__x",
      "data-bascik-prop-title",
    );

    const templateArb = fc.constantFrom(
      '<strong data-bascik-prop-label></strong>',
      '<p data-bascik-prop-label>fallback</p>',
      '<span data-bascik-prop-label="default"></span>',
      '<div class="wrap"><em data-bascik-prop-label></em></div>',
    );

    fc.assert(
      fc.property(propValueArb, templateArb, (value, template) => {
        expect(() => injectProps(template, { label: value })).not.toThrow();
        const result = injectProps(template, { label: value });
        expect(typeof result).toBe("string");
        // The injected value must appear verbatim in the output
        if (value.length > 0) {
          expect(result).toContain(value);
        }
        // No prop markers should remain for a prop that was provided
        expect(result).not.toMatch(/data-bascik-prop-label(?=[>\s])/);
      }),
      { numRuns: 100 },
    );
  });
});
