// This Map was generated by an LLM
export const MIME_MAP = new Map([
  // Text
  [".css", "text/css; charset=utf-8"],
  [".csv", "text/csv; charset=utf-8"],
  [".txt", "text/plain; charset=utf-8"],
  [".xml", "text/xml; charset=utf-8"],
  [".ics", "text/calendar; charset=utf-8"],
  [".js", "application/javascript; charset=utf-8"],
  [".mjs", "application/javascript; charset=utf-8"],
  [".ts", "application/typescript; charset=utf-8"],

  // JSON / Data
  [".json", "application/json; charset=utf-8"],
  [".geojson", "application/geo+json; charset=utf-8"],
  [".map", "application/json; charset=utf-8"],

  // Images
  [".png", "image/png"],
  [".jpg", "image/jpeg"],
  [".jpeg", "image/jpeg"],
  [".gif", "image/gif"],
  [".webp", "image/webp"],
  [".ico", "image/x-icon"],
  [".svg", "image/svg+xml"],
  [".tiff", "image/tiff"],
  [".bmp", "image/bmp"],
  [".avif", "image/avif"],
  [".apng", "image/apng"],

  // Fonts
  [".woff", "font/woff"],
  [".woff2", "font/woff2"],
  [".ttf", "font/ttf"],
  [".otf", "font/otf"],
  [".eot", "application/vnd.ms-fontobject"],

  // Audio
  [".mp3", "audio/mpeg"],
  [".wav", "audio/wav"],
  [".ogg", "audio/ogg"],
  [".m4a", "audio/mp4"],
  [".aac", "audio/aac"],
  [".weba", "audio/webm"],

  // Video
  [".mp4", "video/mp4"],
  [".m4v", "video/mp4"],
  [".mov", "video/quicktime"],
  [".webm", "video/webm"],
  [".ogv", "video/ogg"],
  [".avi", "video/x-msvideo"],
  [".mkv", "video/x-matroska"],

  // Archives / Binary
  [".zip", "application/zip"],
  [".tar", "application/x-tar"],
  [".gz", "application/gzip"],
  [".rar", "application/vnd.rar"],
  [".7z", "application/x-7z-compressed"],
  [".exe", "application/octet-stream"],
  [".bin", "application/octet-stream"],
  [".msi", "application/octet-stream"],
  [".dmg", "application/octet-stream"],

  // PDF / Docs
  [".pdf", "application/pdf"],
  [".doc", "application/msword"],
  [".docx", "application/vnd.openxmlformats-officedocument.wordprocessingml.document"],
  [".xls", "application/vnd.ms-excel"],
  [".xlsx", "application/vnd.openxmlformats-officedocument.spreadsheetml.sheet"],
  [".ppt", "application/vnd.ms-powerpoint"],
  [".pptx", "application/vnd.openxmlformats-officedocument.presentationml.presentation"],

  // Markup / Config
  [".yaml", "application/x-yaml; charset=utf-8"],
  [".yml", "application/x-yaml; charset=utf-8"],
  [".toml", "application/toml; charset=utf-8"],
  [".ini", "text/plain; charset=utf-8"],
  [".md", "text/markdown; charset=utf-8"],

  // Web Assembly & Others
  [".wasm", "application/wasm"],
  [".cjs", "application/javascript; charset=utf-8"],
  [".lock", "text/plain; charset=utf-8"],
  [".env", "text/plain; charset=utf-8"],

  // Icons & Manifest
  [".webmanifest", "application/manifest+json; charset=utf-8"],
  [".manifest", "text/cache-manifest; charset=utf-8"],
  [".appcache", "text/cache-manifest; charset=utf-8"],

  // Other Applications
  [".rtf", "application/rtf"],
  [".sh", "application/x-sh"],
  [".c", "text/x-c; charset=utf-8"],
  [".cpp", "text/x-c; charset=utf-8"],
  [".h", "text/x-c; charset=utf-8"],
  [".java", "text/x-java-source; charset=utf-8"],
  [".py", "text/x-python; charset=utf-8"],
  [".rb", "text/x-ruby; charset=utf-8"],
  [".go", "text/x-go; charset=utf-8"],

  // Mobile App Files
  [".apk", "application/vnd.android.package-archive"],
  [".ipa", "application/octet-stream"],

  // Fallback
  ["octet-stream", "application/octet-stream"]
]);
