name: Release

# pkg:    git tag v1.0.0 && git push --tags
# create: git tag create-v1.0.0 && git push --tags
on:
  push:
    tags:
      - 'v*.*.*'
      - 'create-v*.*.*'

jobs:
  release:
    name: Publish @bascik/bascik to npm
    if: startsWith(github.ref_name, 'v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        run: yarn pkg:test:ci

      - name: Build
        run: yarn pkg:build

      - name: Publish to npm
        working-directory: pkg
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}

  release-create:
    name: Publish create-bascik to npm
    if: startsWith(github.ref_name, 'create-v')
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v5

      - name: Enable Corepack
        run: corepack enable

      - name: Use Node.js 24
        uses: actions/setup-node@v5
        with:
          node-version: 24
          registry-url: 'https://registry.npmjs.org'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Run tests
        working-directory: create
        run: yarn test:ci

      - name: Build
        working-directory: create
        run: yarn build

      - name: Publish to npm
        working-directory: create
        run: npm publish --provenance --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
